
import conjuntos.ConjuntoADT;
import conjuntos.Conjuntos;
import java.util.ArrayList;
import java.util.Arrays;
import pkg8reinas.Main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alexcesarmoya
 */
public class Cuadricula extends javax.swing.JFrame {

    /**
     * Creates new form Cuadricula
     */
    private int m[][];
    
    private  int max =8;
    
    private static final int Ren =8;
    
    private static final int Col=8;
    
    
    
    private static  ConjuntoADT k = new Conjuntos();
    
    private  static ConjuntoADT c = new Conjuntos();
    
    private  static ConjuntoADT Diag45 = new Conjuntos();
    
    private  static ConjuntoADT Diag135 = new Conjuntos();
    
    public Cuadricula() {
        m = new int [max][max]; 

        initComponents();
    }
    
    public  boolean VerificaCoor(int x, int y){
        
        boolean resp;
        if(!k.contains(x) && !c.contains(y) && !Diag45.contains(x+y) && !Diag135.contains(x-y) ){
            k.add(x);
            c.add(y);
            Diag45.add(x+y);
            Diag135.add(x-y);
            resp = true;
            
            
        }
        else 
            resp = false;
        {
            
        }
        return resp;
    }
    
    public void lugarUsuario(int x, int y){
        k.add(x);
        c.add(y);
        Diag45.add(x+y);
        Diag135.add(x-y);
        
    }
    
    public void elimina(){
        k.removeI();
        c.removeI();
        Diag45.removeI();
        Diag135.removeI();
        
    }
    
    public boolean Sol(int x, int y){
        int i=0;
        int j=0;
        lugarUsuario(x, y);
        
        return Sol(x, y, i, j);
    }
    
    private boolean Sol(int x, int y, int i, int j){
        if(j>=0){
            if(j<Ren){
                if(i<Col){ // significa que no puso nada se gastarin todas las posibilidades 
                    if(y==j){
                        return Sol(x, y, i, j+1);
                    }
                    if(VerificaCoor(i, j)){  // añadir si no es la que puso el  usuario 
                         return Sol(x, y, i=0, j+1);
                    }
                    else {
                        return Sol(x, y, i+1, j);
                    }
                }
                // pongas lo del aux y regresa a columna anterior 
            }
            if(k.size()== Ren){
                return true;
            }
            else {
                if(k.ele(k.size()-1).equals(x)){
                    return Sol(x, y, (int) c.ele(c.size()-1), -1);
                }
                else{
                    int aux1 = (int) k.ele(k.size()-1)+1;
                    int aux2 = (int)c.ele(c.size()-1);
                    elimina();
                    return Sol(x, y, aux1, aux2);
                }
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton00 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton40 = new javax.swing.JRadioButton();
        jRadioButton50 = new javax.swing.JRadioButton();
        jRadioButton60 = new javax.swing.JRadioButton();
        jRadioButton70 = new javax.swing.JRadioButton();
        jRadioButton01 = new javax.swing.JRadioButton();
        jRadioButton02 = new javax.swing.JRadioButton();
        jRadioButton03 = new javax.swing.JRadioButton();
        jRadioButton04 = new javax.swing.JRadioButton();
        jRadioButton05 = new javax.swing.JRadioButton();
        jRadioButton06 = new javax.swing.JRadioButton();
        jRadioButton07 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton41 = new javax.swing.JRadioButton();
        jRadioButton51 = new javax.swing.JRadioButton();
        jRadioButton61 = new javax.swing.JRadioButton();
        jRadioButton71 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jRadioButton42 = new javax.swing.JRadioButton();
        jRadioButton52 = new javax.swing.JRadioButton();
        jRadioButton62 = new javax.swing.JRadioButton();
        jRadioButton72 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton33 = new javax.swing.JRadioButton();
        jRadioButton43 = new javax.swing.JRadioButton();
        jRadioButton53 = new javax.swing.JRadioButton();
        jRadioButton63 = new javax.swing.JRadioButton();
        jRadioButton73 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton44 = new javax.swing.JRadioButton();
        jRadioButton54 = new javax.swing.JRadioButton();
        jRadioButton64 = new javax.swing.JRadioButton();
        jRadioButton74 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton45 = new javax.swing.JRadioButton();
        jRadioButton55 = new javax.swing.JRadioButton();
        jRadioButton65 = new javax.swing.JRadioButton();
        jRadioButton75 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        jRadioButton46 = new javax.swing.JRadioButton();
        jRadioButton56 = new javax.swing.JRadioButton();
        jRadioButton66 = new javax.swing.JRadioButton();
        jRadioButton76 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton37 = new javax.swing.JRadioButton();
        jRadioButton47 = new javax.swing.JRadioButton();
        jRadioButton57 = new javax.swing.JRadioButton();
        jRadioButton67 = new javax.swing.JRadioButton();
        jRadioButton77 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("sol");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jRadioButton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton03ActionPerformed(evt);
            }
        });

        jButton2.setText("reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("el usuario ebe poner a la primer Reina");

        jLabel2.setText("para que el programa ponga las demás");

        jLabel3.setText("si que estas se amenacen entre si ");

        jLabel4.setText("ai quiere probar otra posicion pulse \"reset\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(40, 40, 40)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton01)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton51)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton61)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton71)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton03)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton53)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton63)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton73)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton04)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton54)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton64)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton74))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton05)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton55)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton65)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton75))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton06)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton56)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton66)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton76))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton07)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton57)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton67)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton77))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton02)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton52)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton62)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton72)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton00)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton60)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton70)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jRadioButton10)
                                                        .addComponent(jRadioButton00)
                                                        .addComponent(jRadioButton20)
                                                        .addComponent(jRadioButton30)
                                                        .addComponent(jRadioButton40)
                                                        .addComponent(jRadioButton50)
                                                        .addComponent(jRadioButton60)
                                                        .addComponent(jRadioButton70))
                                                    .addComponent(jLabel1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRadioButton01)
                                                    .addComponent(jRadioButton11)
                                                    .addComponent(jRadioButton21)
                                                    .addComponent(jRadioButton31)
                                                    .addComponent(jRadioButton41)
                                                    .addComponent(jRadioButton51)
                                                    .addComponent(jRadioButton61)
                                                    .addComponent(jRadioButton71)
                                                    .addComponent(jLabel2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jRadioButton02)
                                                        .addComponent(jRadioButton22, javax.swing.GroupLayout.Alignment.TRAILING))
                                                    .addComponent(jRadioButton32)
                                                    .addComponent(jRadioButton42)
                                                    .addComponent(jRadioButton52)
                                                    .addComponent(jRadioButton62)
                                                    .addComponent(jRadioButton72)
                                                    .addComponent(jLabel3)))
                                            .addComponent(jRadioButton12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton03)
                                            .addComponent(jRadioButton13)
                                            .addComponent(jRadioButton23)
                                            .addComponent(jRadioButton33)
                                            .addComponent(jRadioButton43)
                                            .addComponent(jRadioButton53)
                                            .addComponent(jRadioButton63)
                                            .addComponent(jRadioButton73)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jRadioButton04)
                                                .addComponent(jRadioButton24, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(jRadioButton34)
                                            .addComponent(jRadioButton44)
                                            .addComponent(jRadioButton54)
                                            .addComponent(jRadioButton64)
                                            .addComponent(jRadioButton74)))
                                    .addComponent(jRadioButton14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton05)
                                    .addComponent(jRadioButton15)
                                    .addComponent(jRadioButton25)
                                    .addComponent(jRadioButton35)
                                    .addComponent(jRadioButton45)
                                    .addComponent(jRadioButton55)
                                    .addComponent(jRadioButton65)
                                    .addComponent(jRadioButton75))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton06)
                                        .addComponent(jRadioButton26, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jRadioButton36)
                                    .addComponent(jRadioButton46)
                                    .addComponent(jRadioButton56)
                                    .addComponent(jRadioButton66)
                                    .addComponent(jRadioButton76)))
                            .addComponent(jRadioButton16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButton07)
                                .addComponent(jRadioButton27, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jRadioButton37)
                            .addComponent(jRadioButton47)
                            .addComponent(jRadioButton57)
                            .addComponent(jRadioButton67)
                            .addComponent(jRadioButton77)))
                    .addComponent(jRadioButton17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int p = -1;
        int q = -1;
        for(int i=0;i<8;i++){
            for(int j=0;j<0;j++){
                m[i][j]=0;
            }
        }
        
        if(jRadioButton00.isSelected()){
            m[0][0]=1;
            p=0;
            q=0;
            
        }
        if(jRadioButton01.isSelected()){
            m[0][1]=1;
            p=0;
            q=1;
            
        }
        if(jRadioButton02.isSelected()){
            m[0][2]=1;
            p=0;
            q=2;
            
        }
        if(jRadioButton03.isSelected()){
            m[0][3]=1;
            p=0;
            q=3;
        }
        if(jRadioButton04.isSelected()){
            m[0][4]=1;
            p=0;
            q=4;
        }
        if(jRadioButton05.isSelected()){
            m[0][5]=1;
            p=0;
            q=5;
        }
        if(jRadioButton06.isSelected()){
            m[0][6]=1;
            p=0;
            q=6;
        }
        if(jRadioButton07.isSelected()){
            m[0][7]=1;
            p=0;
            q=07;
        }
        if(jRadioButton10.isSelected()){
            m[1][0]=1;
            p=1;
            q=0;
        }
        if(jRadioButton31.isSelected()){
            m[1][1]=1;
            p=1;
            q=1;
        }
        if(jRadioButton12.isSelected()){
            m[1][2]=1;
            p=1;
            q=2;
        }
        if(jRadioButton13.isSelected()){
            m[1][3]=1;
            p=1;
            q=2;
        }
        if(jRadioButton14.isSelected()){
            m[1][4]=1;
            p=1;
            q=4;
        }
        if(jRadioButton15.isSelected()){
            m[1][5]=1;
            p=1;
            q=5;
        }
        if(jRadioButton16.isSelected()){
            m[1][6]=1;
            p=1;
            q=6;
        }
        if(jRadioButton17.isSelected()){
            m[1][7]=1;
            p=1;
            q=7;
        }
        if(jRadioButton20.isSelected()){
            m[2][0]=1;
            p=2;
            q=0;
        }
        if(jRadioButton21.isSelected()){
            m[2][1]=1;
            p=2;
            q=1;
        }
        if(jRadioButton22.isSelected()){
            m[2][2]=1;
            p=2;
            q=2;
        }
        if(jRadioButton23.isSelected()){
            m[2][3]=1;
            p=2;
            q=3;
        }
        if(jRadioButton24.isSelected()){
            m[2][4]=1;
            p=2;
            q=4;
        }
        if(jRadioButton25.isSelected()){
            m[2][5]=1;
            p=2;
            q=5;
        }
        if(jRadioButton26.isSelected()){
            m[2][6]=1;
            p=2;
            q=6;
        }
        if(jRadioButton27.isSelected()){
            m[2][7]=1;
            p=2;
            q=7;
        }
        if(jRadioButton30.isSelected()){
            m[3][0]=1;
            p=3;
            q=0;
            
        }
        if(jRadioButton31.isSelected()){
            m[3][1]=1;
            p=3;
            q=1;
        }
        if(jRadioButton32.isSelected()){
            m[3][2]=1;
            p=3;
            q=2;
        }
        if(jRadioButton33.isSelected()){
            m[3][3]=1;
            p=3;
            q=3;
        }
        if(jRadioButton34.isSelected()){
            m[3][4]=1;
            p=3;
            q=4;
        }
        if(jRadioButton35.isSelected()){
            m[3][5]=1;
            p=3;
            q=5;
        }
        if(jRadioButton36.isSelected()){
            m[3][6]=1;
            p=3;
            q=6;
        }
        if(jRadioButton37.isSelected()){
            m[3][7]=1;
            p=3;
            q=7;
        }
        if(jRadioButton40.isSelected()){
            m[4][0]=1;
            p=4;
            q=0;
        }
        if(jRadioButton41.isSelected()){
            m[4][1]=1;
            p=4;
            q=1;
        }
        if(jRadioButton42.isSelected()){
            m[4][2]=1;
            p=4;
            q=2;
        }
        if(jRadioButton43.isSelected()){
            m[4][3]=1;
            p=4;
            q=3;
        }
        if(jRadioButton44.isSelected()){
            m[4][4]=1;
            p=4;
            q=4;
        }
        if(jRadioButton45.isSelected()){
            m[4][5]=1;
            p=4;
            q=5;
        }
        if(jRadioButton46.isSelected()){
            m[4][6]=1;
            p=4;
            q=6;
        }
        if(jRadioButton47.isSelected()){
            m[4][7]=1;
            p=4;
            q=7;
        }
        if(jRadioButton50.isSelected()){
            m[5][0]=1;
            p=5;
            q=0;
        }
        if(jRadioButton51.isSelected()){
            m[5][1]=1;
            p=5;
            q=1;
        }
        if(jRadioButton52.isSelected()){
            m[5][2]=1;
            p=5;
            q=2;
        }
        if(jRadioButton53.isSelected()){
            m[5][3]=1;
            p=5;
            q=3;
        }
        if(jRadioButton54.isSelected()){
            m[5][4]=1;
            p=5;
            q=4;
        }
        if(jRadioButton55.isSelected()){
            m[5][5]=1;
            p=5;
            q=5;
        }
        if(jRadioButton56.isSelected()){
            m[5][6]=1;
            p=5;
            q=6;
        }
        if(jRadioButton57.isSelected()){
            m[5][7]=1;
            p=5;
            p=7;
        }
        if(jRadioButton60.isSelected()){
            m[6][0]=1;
            p=6;
            q=0;
        }
        if(jRadioButton61.isSelected()){
            m[6][1]=1;
            p=6;
            q=1;
        }
        if(jRadioButton62.isSelected()){
            m[6][2]=1;
            p=6;
            q=2;
        }
        if(jRadioButton63.isSelected()){
            m[6][3]=1;
            p=6;
            q=3;
        }
        if(jRadioButton64.isSelected()){
            m[6][4]=1;
            p=6;
            q=4;
        }
        if(jRadioButton65.isSelected()){
            m[6][5]=1;
            p=6;
            q=5;
        }
        if(jRadioButton66.isSelected()){
            m[6][6]=1;
            p=6;
            q=6;
        }
        if(jRadioButton67.isSelected()){
            m[6][7]=1;
            p=6;
            q=7;
        }
        if(jRadioButton70.isSelected()){
            m[7][0]=1;
            p=7;
            q=0;
        }
        if(jRadioButton71.isSelected()){
            m[7][1]=1;
            p=7;
            q=1;
        }
        if(jRadioButton72.isSelected()){
            m[7][2]=1;
            p=7;
            q=2;
        }
        if(jRadioButton73.isSelected()){
            m[7][3]=1;
            p=7;
            q=3;
        }
        if(jRadioButton74.isSelected()){
            m[7][4]=1;
            p=7;
            q=4;
        }
        if(jRadioButton75.isSelected()){
            m[7][5]=1;
            p=7;
            q=5;
        }
        if(jRadioButton76.isSelected()){
            m[7][6]=1;
            p=7;
            q=6;
        }
        if(jRadioButton77.isSelected()){
            m[7][7]=1;
            p=7;
            q=7;
        }
        
        
        System.out.println("");  
        System.out.println("");
        
        Main ha = new Main();
        
        System.out.println(ha.Sol(p, q));
        
        ArrayList uno = ha.imprimeK();
        ArrayList dos = ha.imprimeC();
        System.out.println(uno.toString());
        System.out.println(dos.toString());
        
        for(int i=0;i<uno.size();i++){
            int v = (int) uno.get(i);
            int w = (int) dos.get(i);
            m[v][w]=2;
        }
        for (int x=0; x < m.length; x++) {
    System.out.println("");
  for (int y=0; y < m[x].length; y++) {
    System.out.print (" "+m[y][x]);
  }
}
        
        if(m[0][0]!=0){
            jRadioButton00.setSelected(true);
        }
        if(m[1][0]!=0){
            jRadioButton10.setSelected(true);
        }
        if(m[2][0]!=0){
            jRadioButton20.setSelected(true);
        }
        if(m[3][0]!=0){
            jRadioButton30.setSelected(true);
        }
        if(m[4][0]!=0){
            jRadioButton40.setSelected(true);
        }
        if(m[5][0]!=0){
            jRadioButton50.setSelected(true);
        }
        if(m[6][0]!=0){
            jRadioButton60.setSelected(true);
        }
        if(m[7][0]!=0){
            jRadioButton70.setSelected(true);
        }
        if(m[0][1]!=0){
            jRadioButton01.setSelected(true);
        }
        if(m[1][1]!=0){
            jRadioButton11.setSelected(true);
        }
        if(m[2][1]!=0){
            jRadioButton21.setSelected(true);
        }
        if(m[3][1]!=0){
            jRadioButton03.setSelected(true);
        }
        if(m[4][1]!=0){
            jRadioButton41.setSelected(true);
        }
        if(m[5][1]!=0){
            jRadioButton51.setSelected(true);
        }
        if(m[6][1]!=0){
            jRadioButton61.setSelected(true);
        }
        if(m[7][1]!=0){
            jRadioButton71.setSelected(true);
        }
        if(m[0][2]!=0){
            jRadioButton02.setSelected(true);
        }
        if(m[1][2]!=0){
            jRadioButton12.setSelected(true);
        }
        if(m[2][2]!=0){
            jRadioButton22.setSelected(true);
        }
        if(m[3][2]!=0){
            jRadioButton32.setSelected(true);
        }
        if(m[4][2]!=0){
            jRadioButton42.setSelected(true);
        }
        if(m[5][2]!=0){
            jRadioButton52.setSelected(true);
        }
        if(m[6][2]!=0){
            jRadioButton62.setSelected(true);
        }
        if(m[7][2]!=0){
            jRadioButton72.setSelected(true);
        }
        if(m[0][3]!=0){
            jRadioButton03.setSelected(true);
        }
        if(m[1][3]!=0){
            jRadioButton13.setSelected(true);
        }
        if(m[2][3]!=0){
            jRadioButton23.setSelected(true);
        }
        if(m[3][3]!=0){
            jRadioButton33.setSelected(true);
        }
        if(m[4][3]!=0){
            jRadioButton43.setSelected(true);
        }
        if(m[5][3]!=0){
            jRadioButton53.setSelected(true);
        }
        if(m[6][3]!=0){
            jRadioButton63.setSelected(true);
        }
        if(m[7][3]!=0){
            jRadioButton73.setSelected(true);
        }
        if(m[0][4]!=0){
            jRadioButton04.setSelected(true);
        }
        if(m[1][4]!=0){
            jRadioButton14.setSelected(true);
        }
        if(m[2][4]!=0){
            jRadioButton24.setSelected(true);
        }
        if(m[3][4]!=0){
            jRadioButton34.setSelected(true);
        }
        if(m[4][4]!=0){
            jRadioButton44.setSelected(true);
        }
        if(m[5][4]!=0){
            jRadioButton54.setSelected(true);
        }
        if(m[6][4]!=0){
            jRadioButton64.setSelected(true);
        }
        if(m[7][4]!=0){
            jRadioButton74.setSelected(true);
        }
        if(m[0][5]!=0){
            jRadioButton05.setSelected(true);
        }
        if(m[1][5]!=0){
            jRadioButton15.setSelected(true);
        }
        if(m[2][5]!=0){
            jRadioButton25.setSelected(true);
        }
        if(m[3][5]!=0){
            jRadioButton35.setSelected(true);
        }
        if(m[4][5]!=0){
            jRadioButton45.setSelected(true);
        }
        if(m[5][5]!=0){
            jRadioButton55.setSelected(true);
        }
        if(m[6][5]!=0){
            jRadioButton65.setSelected(true);
        }
        if(m[7][5]!=0){
            jRadioButton75.setSelected(true);
        }
        if(m[0][6]!=0){
            jRadioButton06.setSelected(true);
        }
        if(m[1][6]!=0){
            jRadioButton16.setSelected(true);
        }
        if(m[2][6]!=0){
            jRadioButton26.setSelected(true);
        }
        if(m[3][6]!=0){
            jRadioButton36.setSelected(true);
        }
        if(m[4][6]!=0){
            jRadioButton46.setSelected(true);
        }
        if(m[5][6]!=0){
            jRadioButton56.setSelected(true);
        }
        if(m[6][6]!=0){
            jRadioButton66.setSelected(true);
        }
        if(m[7][6]!=0){
            jRadioButton76.setSelected(true);
        }
        if(m[0][7]!=0){
            jRadioButton07.setSelected(true);
        }
        if(m[1][7]!=0){
            jRadioButton17.setSelected(true);
        }
        if(m[2][7]!=0){
            jRadioButton27.setSelected(true);
        }
        if(m[3][7]!=0){
            jRadioButton37.setSelected(true);
        }
        if(m[4][7]!=0){
            jRadioButton47.setSelected(true);
        }
        if(m[5][7]!=0){
            jRadioButton57.setSelected(true);
        }
        if(m[6][7]!=0){
            jRadioButton67.setSelected(true);
        }
        if(m[7][7]!=0){
            jRadioButton77.setSelected(true);
        }
        
        
        
        
        System.out.println("");
        System.out.println("");
        
        for (int x=0; x < m.length; x++) {
    System.out.println("");
  for (int y=0; y < m[x].length; y++) {
    System.out.print (" "+m[y][x]);
  }
}
        
        
        
        
        
                
        
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton03ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
        for(int i=0;i<m.length;i++){
            for(int j=0;j<0;j++){
                m[i][j]=0;
            }
        }
        
        
            jRadioButton00.setSelected(false);
        
        
            jRadioButton10.setSelected(false);
        
        
            jRadioButton20.setSelected(false);
        
        
            jRadioButton30.setSelected(false);
        
        
            jRadioButton40.setSelected(false);
        
        
            jRadioButton50.setSelected(false);
        
        
            jRadioButton60.setSelected(false);
        
        
            jRadioButton70.setSelected(false);
        
        
            jRadioButton01.setSelected(false);
        
        
            jRadioButton11.setSelected(false);
        
        
            jRadioButton21.setSelected(false);
        
        
            jRadioButton03.setSelected(false);
        
        
            jRadioButton41.setSelected(false);
        
        
            jRadioButton51.setSelected(false);
        
        
            jRadioButton61.setSelected(false);
        
        
            jRadioButton71.setSelected(false);
        
        
            jRadioButton02.setSelected(false);
        
        
            jRadioButton12.setSelected(false);
        
        
            jRadioButton22.setSelected(false);
        
        
            jRadioButton32.setSelected(false);
        
        
            jRadioButton42.setSelected(false);
        
        
            jRadioButton52.setSelected(false);
        
        
            jRadioButton62.setSelected(false);
        
        
            jRadioButton72.setSelected(false);
        
        
            jRadioButton03.setSelected(false);
        
        
            jRadioButton13.setSelected(false);
        
        
            jRadioButton23.setSelected(false);
        
        
            jRadioButton33.setSelected(false);
        
        
            jRadioButton43.setSelected(false);
        
        
            jRadioButton53.setSelected(false);
        
        
            jRadioButton63.setSelected(false);
        
        
            jRadioButton73.setSelected(false);
        
        
            jRadioButton04.setSelected(false);
        
        
            jRadioButton14.setSelected(false);
        
        
            jRadioButton24.setSelected(false);
        
        
            jRadioButton34.setSelected(false);
        
        
            jRadioButton44.setSelected(false);
        
        
            jRadioButton54.setSelected(false);
        
        
            jRadioButton64.setSelected(false);
        
        
            jRadioButton74.setSelected(false);
        
        
            jRadioButton05.setSelected(false);
        
        
            jRadioButton15.setSelected(false);
        
        
            jRadioButton25.setSelected(false);
        
        
            jRadioButton35.setSelected(false);
        
        
            jRadioButton45.setSelected(false);
        
        
            jRadioButton55.setSelected(false);
        
        
            jRadioButton65.setSelected(false);
        
        
            jRadioButton75.setSelected(false);
        
        
            jRadioButton06.setSelected(false);
        
        
            jRadioButton16.setSelected(false);
        
        
            jRadioButton26.setSelected(false);
        
        
            jRadioButton36.setSelected(false);
        
        
            jRadioButton46.setSelected(false);
        
        
            jRadioButton56.setSelected(false);
        
        
            jRadioButton66.setSelected(false);
        
        
            jRadioButton76.setSelected(false);
        
        
            jRadioButton07.setSelected(false);
        
        
            jRadioButton17.setSelected(false);
        
        
            jRadioButton27.setSelected(false);
        
        
            jRadioButton37.setSelected(false);
        
        
            jRadioButton47.setSelected(false);
        
        
            jRadioButton57.setSelected(false);
        
        
            jRadioButton67.setSelected(false);
        
        
            jRadioButton77.setSelected(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        System.out.println();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuadricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuadricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuadricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuadricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuadricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton00;
    private javax.swing.JRadioButton jRadioButton01;
    private javax.swing.JRadioButton jRadioButton02;
    private javax.swing.JRadioButton jRadioButton03;
    private javax.swing.JRadioButton jRadioButton04;
    private javax.swing.JRadioButton jRadioButton05;
    private javax.swing.JRadioButton jRadioButton06;
    private javax.swing.JRadioButton jRadioButton07;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JRadioButton jRadioButton37;
    private javax.swing.JRadioButton jRadioButton40;
    private javax.swing.JRadioButton jRadioButton41;
    private javax.swing.JRadioButton jRadioButton42;
    private javax.swing.JRadioButton jRadioButton43;
    private javax.swing.JRadioButton jRadioButton44;
    private javax.swing.JRadioButton jRadioButton45;
    private javax.swing.JRadioButton jRadioButton46;
    private javax.swing.JRadioButton jRadioButton47;
    private javax.swing.JRadioButton jRadioButton50;
    private javax.swing.JRadioButton jRadioButton51;
    private javax.swing.JRadioButton jRadioButton52;
    private javax.swing.JRadioButton jRadioButton53;
    private javax.swing.JRadioButton jRadioButton54;
    private javax.swing.JRadioButton jRadioButton55;
    private javax.swing.JRadioButton jRadioButton56;
    private javax.swing.JRadioButton jRadioButton57;
    private javax.swing.JRadioButton jRadioButton60;
    private javax.swing.JRadioButton jRadioButton61;
    private javax.swing.JRadioButton jRadioButton62;
    private javax.swing.JRadioButton jRadioButton63;
    private javax.swing.JRadioButton jRadioButton64;
    private javax.swing.JRadioButton jRadioButton65;
    private javax.swing.JRadioButton jRadioButton66;
    private javax.swing.JRadioButton jRadioButton67;
    private javax.swing.JRadioButton jRadioButton70;
    private javax.swing.JRadioButton jRadioButton71;
    private javax.swing.JRadioButton jRadioButton72;
    private javax.swing.JRadioButton jRadioButton73;
    private javax.swing.JRadioButton jRadioButton74;
    private javax.swing.JRadioButton jRadioButton75;
    private javax.swing.JRadioButton jRadioButton76;
    private javax.swing.JRadioButton jRadioButton77;
    // End of variables declaration//GEN-END:variables
}
